[package]
name = "bevy-chess"
version = "0.1.0"
edition = "2021"
authors = ["rust@jbcurtin.io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { branch = "main", git = "https://github.com/bevyengine/bevy.git" }